services:
  kuma:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data/kuma:/app/data

  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    command: serve
    restart: unless-stopped
    environment:
      - NTFY_BASE_URL=https://notif.ydinar.fr
    volumes:
      - ./data/ntfy:/var/lib/ntfy

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
